#! /usr/bin/python3

import fqapi
client = fqapi.WrappingLocalClient()

def mailbox(row):
    disabled = '' if row['mailbox-enabled'] else '(disabled)'
    return 'vmspool/{}{}'.format(row['name'].replace('.', ':'), disabled) if row['has-mailbox'] else '-'

data = client.get('/1/email/accounts')
print('User Mailbox Aliases')
for row in data['accounts']:
    print(row['name'], mailbox(row), ' '.join(row['forwards']))
