#! /usr/bin/python3

import argparse
parser = argparse.ArgumentParser(description='')
parser.add_argument('username', metavar='USERNAME', type=str)
parser.add_argument('addresses', metavar='ADDRESS', type=str, nargs='*')
args = parser.parse_args()

import fqapi
client = fqapi.WrappingLocalClient()

if '/' in args.username:
    print('vaddalias: Invalid username:', args.username)
    exit(1)

ref = '/1/email/accounts/{}'.format(args.username)
client.errormsgs[404] = None
client.errormsgs[200] = 'Username {!r} already exists'.format(args.username)
client.get(ref)

client.errormsgs[200] = None
client.put(ref, {
    'name': args.username,
    'forwards': args.addresses,
    'mailbox-enabled': False,
    })
print("vaddalias: user '{}' successfully added".format(args.username))
