#! /usr/bin/python3

import argparse
parser = argparse.ArgumentParser(description='Test authentication against a mail account.')
parser.add_argument('username', metavar='USERNAME', type=str)
args = parser.parse_args()

import fqapi
client = fqapi.LocalClient()

password = input().rstrip('\r\n')

try:
    _, _, data = client.post('/1/email/authenticate', {
        'username': args.username,
        'password': password,
    })
except fqapi.Error:
    exit(111)
exit(0 if data['authenticated'] else 1)
