#! /usr/bin/python3

import argparse
parser = argparse.ArgumentParser(description='Change a forwarding alias in your mail accounts.')
parser.add_argument('username', metavar='USERNAME', type=str)
parser.add_argument('addresses', metavar='ADDRESS', type=str, nargs='*')
args = parser.parse_args()

import fqapi
client = fqapi.WrappingLocalClient()

if '/' in args.username:
    print('vchalias: Invalid username:', args.username)
    exit(1)
client.errormsgs[404] = 'Unknown username: {!r}'.format(args.username)
client.get('/1/email/accounts/{}'.format(args.username))
client.put('/1/email/accounts/{}'.format(args.username), {
    'forwards': args.addresses,
    })
print("vchalias: User '{}' successfully changed.".format(args.username))
