#! /usr/bin/python2
from __future__ import print_function

import argparse
parser = argparse.ArgumentParser(description='Change a forwarding alias in your mail accounts.')
parser.add_argument('username', metavar='USERNAME', type=str)
parser.add_argument('addresses', metavar='ADDRESS', type=str, nargs='*')
args = parser.parse_args()

import fqapi
client = fqapi.LocalClient()

if '/' in args.username:
    print('vchalias: Invalid username:', args.username)
    exit(1)
try:
    client.request('GET', '/1/email/accounts/{}'.format(args.username))
except fqapi.Error as e:
    if e.code == 404:
        print('vchalias: Invalid username:', args.username)
    else:
        print('vchalias: API Error:', e.code, e.msg)
    exit(1)

client.request('PUT', '/1/email/accounts/{}'.format(args.username), {
    'forwards': args.addresses,
    })
print("vchalias: User '{}' successfully changed.".format(args.username))
