#! /usr/bin/python2
from __future__ import print_function

import argparse
parser = argparse.ArgumentParser(description='Delete users from your mail accounts.')
parser.add_argument('usernames', metavar='USERNAME', type=str, nargs='+')
args = parser.parse_args()

import fqapi
client = fqapi.LocalClient()

_, _, accounts = client.request('GET', '/1/email/accounts')
accounts = dict([ (a['name'], a) for a in accounts['accounts'] ])

for username in args.usernames:
    if username not in accounts or accounts[username]['mailbox-enabled']:
        print("vdelalias: Error: Account named '{}' is not an alias".format(username))
        exit(100)
    client.request('DELETE', '/1/email/accounts/{}'.format(username))
    print("vdelalias: user '{}' successfully deleted.".format(username))
