#! /usr/bin/python3
import getpass, os

import argparse
parser = argparse.ArgumentParser(description='Change the password of a mail account.')
parser.add_argument('username', metavar='USERNAME', type=str)
args = parser.parse_args()

import fqapi
client = fqapi.WrappingLocalClient()

if '/' in args.username:
    print('vpasswd: Invalid username:', args.username)
    exit(1)
client.errormsgs[404] = 'Unknown username: {!r}'.format(args.username)
client.get('/1/email/accounts/{}'.format(args.username))

if os.isatty(0):
    pass1 = getpass.getpass("Enter the user's new password: ")
    pass2 = getpass.getpass("Please type it again for verification: ")
    if pass1 != pass2:
        print("vpasswd: error: passwords don't match")
        exit(1)
else:
    pass1 = input()

if pass1 == "":
    print("vpasswd: error: password is empty")
    exit(1)

client.put('/1/email/accounts/{}'.format(args.username), {
    'password': pass1,
    })
print("vpasswd: Password for user '{}' successfully changed.".format(args.username))
